server:
  #运行端口
  port: 9099
eureka:
  instance:
    #注册ip
    hostname: loaclhost
  client:
    #禁止自己当做服务注册
    register-with-eureka: false
    #屏蔽注册信息
    fetch-registry: false
    #注册url
    service-url:
      defalutZone: http://${eureka.instance.hostname}:${server.port}/eureka/