eureka:
  client:
    serviceUrl:
      # 服务注册地址
      defaultZone: http://localhost:9099/eureka

# 运行端口
server:
  port: 8766

# 应用名称
spring:
  application:
    name: yeyu-cloud-client
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
  resources:
    static-locations: classpath:/static/
  security:
    user:
      name: user
      password: user
  # 数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.100:3306/smspj?serverTimezone=GTM&useUnicode=true&characterEncoding=utf-8
    username: root
    password: Yeyu200043
    type: com.alibaba.druid.pool.DruidDataSource
    # 数据源配置
    # 初始化连接个数
    initiialSize: 5
    # 最小连接池数
    minIdle: 5
    # 最大连接池数
    maxActive: 201
    # 获取连接时最大等待时间，单位毫秒
    maxWait: 60000
    # 间隔多久进行一次检测，检测需要关闭空闲连接，单位毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 连接保持空闲不被回收的最小时间
    minEvictableIdleTimeMillis: 300000
    # 用来检测连接是否有效的sql，要求是一个查询语句
    validationQuery: SELECT 1 FROM DUAL
    # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
    testWhileIdle: true
    # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
    testOnBorrow: false
    # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
    testOnReturn: false
    # 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
    poolPreparedStatements: true
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
    maxPoolPreparedStatementPerConnectionSize: 20
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml


